"""
Deskpilot — conversation sessions.

One JSONL file per session under private/files/copilot_sessions/<sid>.jsonl:
    line 0 : header  {"user":..., "created_at":..., "v":1}
    line n : message {"role":"user"|"assistant", "content":..., "ts":...}
             or meta {"role":"_meta", "kind":"attachment"|"extract", ...}

WHY TEXT-ONLY HISTORY
---------------------
We deliberately DO NOT persist `tool_calls` / role:"tool" messages. An assistant
message carrying tool_calls must be immediately followed by its matching tool
responses or vLLM/OpenAI rejects the whole request with HTTP 400 — and any
turn-count truncation will eventually slice such a block in half. Storing only
the user/assistant prose makes truncation structurally safe and keeps the prompt
small, which matters directly: 429 (queue full) is this deployment's #1 error.

The system message is NEVER persisted — api.py rebuilds it every turn so the
model always sees the CURRENT screen context, not the screen the user left ten
minutes ago.

No `File` doc is created for these transcripts: a File doc would make them
downloadable and attachable by other users.
"""

import json
import os
import time

import frappe

from deskpilot import config

SESSION_DIR = "copilot_sessions"
MAX_TURNS = 12               # user+assistant pairs replayed to the model
IDLE_EXPIRY_SEC = 24 * 3600      # after this a NEW chat starts on next visit
RETENTION_SEC = 7 * 24 * 3600    # ...but the transcript stays browsable this long
LIST_LIMIT = 25
MAX_MSG_CHARS = 8000         # per stored message
RATE_LIMIT_N = 30            # asks ...
RATE_LIMIT_WINDOW = 60       # ... per this many seconds, per user
LOCK_WAIT_SEC = 2


# ------------------------------------------------------------------ paths

def _dir():
    d = os.path.join(frappe.get_site_path("private", "files"), SESSION_DIR)
    os.makedirs(d, exist_ok=True)
    return d


def _path(sid):
    # sid is generated by us (hex); refuse anything that could escape the dir
    if not sid or not str(sid).isalnum():
        return None
    return os.path.join(_dir(), str(sid) + ".jsonl")


# --------------------------------------------------------------- lifecycle

def create(user=None):
    sid = frappe.generate_hash(length=16)
    user = user or frappe.session.user
    with open(_path(sid), "w") as f:
        f.write(json.dumps({"user": user, "created_at": time.time(), "v": 1}) + "\n")
    return sid


def _read(sid):
    """Return (header, [lines]) or (None, []) if missing/corrupt."""
    p = _path(sid)
    if not p or not os.path.exists(p):
        return None, []
    try:
        with open(p) as f:
            raw = [l for l in f.read().splitlines() if l.strip()]
        if not raw:
            return None, []
        header = json.loads(raw[0])
        rows = []
        for l in raw[1:]:
            try:
                rows.append(json.loads(l))
            except Exception:
                continue
        return header, rows
    except Exception:
        return None, []


def resolve(sid, user=None):
    """Return a VALID session id for this user, creating a new one if needed.

    Returns (sid, is_new). A session is rejected (and replaced) when it is
    missing, owned by another user, or idle for more than IDLE_EXPIRY_SEC.
    """
    user = user or frappe.session.user
    header, rows = _read(sid) if sid else (None, [])
    if not header:
        return create(user), True
    if header.get("user") != user:            # never hand a session across users
        return create(user), True
    last = rows[-1]["ts"] if rows and rows[-1].get("ts") else header.get("created_at", 0)
    if time.time() - float(last or 0) > IDLE_EXPIRY_SEC:
        return create(user), True
    return sid, False


def append(sid, role, content, **extra):
    p = _path(sid)
    if not p or not os.path.exists(p):
        return
    rec = {"role": role, "content": str(content or "")[:MAX_MSG_CHARS], "ts": time.time()}
    rec.update(extra)
    try:
        with open(p, "a") as f:
            f.write(json.dumps(rec, default=str) + "\n")
    except Exception:
        frappe.log_error(frappe.get_traceback(), "deskpilot session append")


def history(sid, max_turns=MAX_TURNS):
    """Bounded, replay-safe message list: user/assistant prose only."""
    _, rows = _read(sid)
    msgs = [
        {"role": r["role"], "content": r.get("content") or ""}
        for r in rows
        if r.get("role") in ("user", "assistant") and (r.get("content") or "").strip()
    ]
    return msgs[-(max_turns * 2):]


# ---------------------------------------------------- attachment registry

def register_attachment(sid, meta):
    """Remember a file the user attached in this session (name/type/url)."""
    append(sid, "_meta", "", kind="attachment", file=meta)


def attachments(sid):
    _, rows = _read(sid)
    out, seen = [], set()
    for r in rows:
        if r.get("kind") == "attachment" and r.get("file"):
            u = r["file"].get("url")
            if u and u not in seen:
                seen.add(u)
                out.append(r["file"])
    return out


def cache_extract(sid, url, text):
    append(sid, "_meta", "", kind="extract", url=url, text=str(text or "")[:30000])


def get_extract(sid, url):
    _, rows = _read(sid)
    for r in reversed(rows):
        if r.get("kind") == "extract" and r.get("url") == url:
            return r.get("text")
    return None


# ------------------------------------------------------- limits & locking

def rate_limit_ok(user=None):
    """Simple fixed-window counter in redis. True = allowed."""
    user = user or frappe.session.user
    key = "copilot:rl:%s:%d" % (user, int(time.time()) // RATE_LIMIT_WINDOW)
    cache = frappe.cache()
    try:
        n = cache.incr(key)
        if n == 1:
            cache.expire(key, RATE_LIMIT_WINDOW * 2)
        return n <= RATE_LIMIT_N
    except Exception:
        return True          # never let the limiter itself break the copilot


def lock(sid):
    """Context manager: one in-flight ask per session."""
    return frappe.cache().lock("copilot:session:" + str(sid), timeout=600,
                               blocking_timeout=LOCK_WAIT_SEC)


# -------------------------------------------------------------- housekeeping

def purge(max_age_sec=None):
    """Delete idle/expired session files. Returns (removed, kept, urls_freed)."""
    if max_age_sec is None:
        max_age_sec = config.get_int("session_retention_sec", RETENTION_SEC)
    d = _dir()
    removed, kept, urls = 0, 0, []
    now = time.time()
    for fn in os.listdir(d):
        if not fn.endswith(".jsonl"):
            continue
        p = os.path.join(d, fn)
        try:
            if now - os.path.getmtime(p) <= max_age_sec:
                kept += 1
                continue
            sid = fn[:-6]
            for a in attachments(sid):
                if a.get("url"):
                    urls.append(a["url"])
            os.remove(p)
            removed += 1
        except Exception:
            continue
    return removed, kept, urls


# ------------------------------------------------------- history browsing

def list_for_user(user=None, limit=LIST_LIMIT):
    """Recent conversations belonging to this user, newest first.

    Titles come from the first thing the user actually said, so the list reads
    like a chat history rather than a list of opaque ids.
    """
    user = user or frappe.session.user
    out = []
    try:
        names = os.listdir(_dir())
    except Exception:
        return out
    for fn in names:
        if not fn.endswith(".jsonl"):
            continue
        sid = fn[:-6]
        header, rows = _read(sid)
        if not header or header.get("user") != user:
            continue                      # never leak another user's conversation
        msgs = [r for r in rows if r.get("role") in ("user", "assistant")
                and (r.get("content") or "").strip()]
        if not msgs:
            continue                      # empty shell, nothing to show
        first_user = next((r["content"] for r in msgs if r["role"] == "user"), "")
        last = msgs[-1]
        out.append({
            "session_id": sid,
            "title": (first_user or "Conversation").strip()[:70],
            "preview": (last.get("content") or "").strip()[:90],
            "turns": sum(1 for r in msgs if r["role"] == "user"),
            "updated": last.get("ts") or header.get("created_at") or 0,
        })
    out.sort(key=lambda x: x.get("updated") or 0, reverse=True)
    return out[:limit]


def transcript(sid, user=None):
    """User/assistant transcript for re-rendering, or None if not this user's."""
    user = user or frappe.session.user
    header, rows = _read(sid)
    if not header or header.get("user") != user:
        return None
    return [{"role": r["role"], "content": r.get("content") or "", "ts": r.get("ts")}
            for r in rows if r.get("role") in ("user", "assistant")
            and (r.get("content") or "").strip()]
